local:
  DETECTOR_MODEL_PATH: "D:/prographer/process/prographer_detector.pth"
  ENCODER_MODEL_PATH: "D:/prographer/process/prographer_encoder.pth"
  malicious_intervals: "D:/prographer/malicious_intervals.txt"

remote:
  DETECTOR_MODEL_PATH: "/home/nsas2020/fuzz/prographer/process/prographer_detector.pth"
  ENCODER_MODEL_PATH: "/home/nsas2020/fuzz/prographer/process/prographer_encoder.pth"
  malicious_intervals: "/home/nsas2020/fuzz/prographer/malicious_intervals.txt"